In [68]:
import pandas as pd
from evaluate import *
from overlap_evaluate import *

import json

In [69]:
results = pd.read_csv("results/nq/t5-xl-ssm-nq_results.csv")

In [70]:
results.head()

,question,id,answers,prediction,overlap,em,f1,bert_score,meteor_score
0,who got the first nobel prize in physics,0,['Wilhelm Conrad Röntgen'],Wilhelm Conrad Röntgen,"['total', 'answer_overlap']",True,1.0,1.00000,0.981481
1,when is the next deadpool movie being released,1,"['May 18 , 2018']","May 18, 2018","['total', 'answer_overlap']",True,1.0,0.75861,0.992188
2,which mode is used for short wave broadcast se...,2,"['Olivia', 'MFSK']",CW,"['total', 'answer_overlap']",False,0.0,0.29394,0.000000
3,the south west wind blows across nigeria between,3,['till September'],between April and October,"['total', 'no_answer_overlap']",False,0.0,0.25939,0.000000
4,what does hp mean in war and order,4,['hit points or health points'],Heuristically programmed,"['total', 'no_answer_overlap']",False,0.0,-0.06745,0.000000

In [71]:
wrong_results = results[results['em'] == False]
tmp = []
for index, item in wrong_results.iterrows():
    # print(index)
    if 'no_answer_overlap' in ast.literal_eval(item['overlap']):
        tmp.append(dict(item))

In [72]:
no_overlap = pd.DataFrame(tmp)

In [73]:
no_overlap = no_overlap.sort_values('bert_score', ascending=False)

In [74]:
no_overlap[0:25]

,question,id,answers,prediction,overlap,em,f1,bert_score,meteor_score
307,when does canada switch to daylight savings time,828,['the second Sunday of March'],the second Sunday in March,"['total', 'no_answer_overlap']",False,0.750000,0.95117,0.750000
413,when did the first battle of ypres end,1143,['22 November 1914'],30 November 1914,"['total', 'no_answer_overlap']",False,0.666667,0.94158,0.625000
440,what is the latest version of chrome for linux,1229,"['67.0', '67.0. 3396']",63.0,"['total', 'no_answer_overlap']",False,0.000000,0.91343,0.000000
1030,what is the minimum dollar amount for federal ...,3067,"['$75,000']","$15,000","['total', 'no_answer_overlap']",False,0.000000,0.90510,0.250000
165,what is the average height of a chinese man,442,['5 ft 6 in'],5 ft 10 in,"['total', 'no_answer_overlap']",False,0.750000,0.90364,0.638889
976,when was the south asian association for regio...,2904,"['December 1985', '8 December 1985']",8 August 1985,"['total', 'no_answer_overlap']",False,0.666667,0.88036,0.333333
869,how many customers does edf have in the uk,2565,"['5.7 million', '5.7 million customer accounts']",1.4 million,"['total', 'no_answer_overlap']",False,0.500000,0.87846,0.250000
433,where does the red river start and end in loui...,1211,['the Texas Panhandle'],in the Texas Panhandle,"['total', 'no_answer_overlap']",False,0.800000,0.87300,0.949821
586,the complete collection of dna and genes is ca...,1655,"['genome', 'chromosome']",chromosomes,"['total', 'no_answer_overlap']",False,0.000000,0.86578,0.500000
912,where are alkali metals located on the periodi...,2698,"['group 1', 'in the s - block']",group 2,"['total', 'no_answer_overlap']",False,0.500000,0.86458,0.250000
391,where are the san juan mountains in new mexico,1053,['northwestern New Mexico'],northern New Mexico,"['total', 'no_answer_overlap']",False,0.666667,0.86437,0.625000
466,who was the first president of the constituent...,1303,['Dr. Rajendra Prasad'],"Dr. Rajendra Prasad, INC","['total', 'no_answer_overlap']",False,0.857143,0.85198,0.920139
395,who played john connor in the original terminator,1082,"['Edward Furlong', 'Michael Edwards']",Edward Walter Furlong,"['total', 'no_answer_overlap']",False,0.800000,0.84793,0.476190
1139,how much does a new gulfstream g650 cost,3345,"['US $ 66.61 million', '$66.5 million']",$66.61 million,"['total', 'no_answer_overlap', 'question_overl...",False,0.800000,0.83101,0.754986
1029,when did the vikings first sail and reach britain,3066,"['786 -- 802', '6 January 793']",8 June 793,"['total', 'no_answer_overlap']",False,0.333333,0.82996,0.166667
298,when did beryl markham fly across the atlantic,805,"['4 September 1936', 'September 1936']",July 1934,"['total', 'no_answer_overlap']",False,0.000000,0.82745,0.000000
516,who was assassinated during a visit to sarajev...,1462,['Archduke Franz Ferdinand of Austria'],Archduke Franz Ferdinand,"['total', 'no_answer_overlap', 'no_question_ov...",False,0.750000,0.82541,0.613426
1046,who played shmuel in the boy in the striped py...,3099,['Jack Scanlon'],Jack Charles Scanlon,"['total', 'no_answer_overlap']",False,0.800000,0.82250,0.476190
618,what is a coherent set of values and beliefs a...,1729,"['a political ideology', 'political ideology',...",a political philosophy,"['total', 'no_answer_overlap']",False,0.500000,0.82127,0.625000
231,total goals scored by ronaldo in la liga,634,['309'],311,"['total', 'no_answer_overlap', 'no_question_ov...",False,0.000000,0.81769,0.000000
653,when does jim propose to pam on the office,1837,['In the Season 5 premiere'],in the season eight premiere,"['total', 'no_answer_overlap']",False,0.750000,0.80807,0.750000
546,when did the soviet union first gain control o...,1532,['14 June 1940'],17 September 1939,"['total', 'no_answer_overlap', 'no_question_ov...",False,0.000000,0.80312,0.000000
194,when is the new dumping ground coming out 2017,522,['15 December 2017'],13 October 2017,"['total', 'no_answer_overlap', 'no_question_ov...",False,0.333333,0.79609,0.166667
497,who pays medical bills in great britain where ...,1400,"['general taxation', 'taxes']",general taxation system,"['total', 'no_answer_overlap']",False,0.800000,0.79533,0.892857
373,when does april fools day end at noon,1006,['April 1st'],April 1,"['total', 'no_answer_overlap']",False,0.500000,0.79509,0.250000

In [75]:
no_overlap.sort_values('meteor_score', ascending=False)[0:50]

,question,id,answers,prediction,overlap,em,f1,bert_score,meteor_score
765,what is the name of the restaurant in seinfeld,2233,"[""Monk 's"", ""Monk 's Café""]",Monk's Café,"['total', 'no_answer_overlap']",False,0.400000,0.74776,0.981481
433,where does the red river start and end in loui...,1211,['the Texas Panhandle'],in the Texas Panhandle,"['total', 'no_answer_overlap']",False,0.800000,0.87300,0.949821
62,when did the the regulatory reform ( fire safe...,155,['1 October 2006'],on 1 October 2006,"['total', 'no_answer_overlap']",False,0.857143,0.74513,0.949821
317,where is the tablet of the ten commandments,856,['Ark of the Covenant'],on the Ark of the Covenant,"['total', 'no_answer_overlap']",False,0.857143,0.70053,0.944940
278,a good that can be used in place of another good,752,"['substitute good', 'A substitute good']",substitute goods,"['total', 'no_answer_overlap', 'no_question_ov...",False,0.500000,0.63368,0.937500
466,who was the first president of the constituent...,1303,['Dr. Rajendra Prasad'],"Dr. Rajendra Prasad, INC","['total', 'no_answer_overlap']",False,0.857143,0.85198,0.920139
213,which episode does gideon die in criminal minds,578,"[""`` Nelson 's Sparrow ''"", ""Nelson 's Sparrow""]","""Nelson's Sparrow""","['total', 'no_answer_overlap', 'no_question_ov...",False,0.400000,0.54157,0.920139
484,which is the ring finger for male in india,1360,"['left ring finger', 'the left ring finger']",ring finger of the left,"['total', 'no_answer_overlap']",False,0.857143,0.59684,0.914634
1200,where does the electron transport chain get it...,3536,"['donor molecule', 'electron donors']",from electron donors,"['total', 'no_answer_overlap']",False,0.800000,0.34920,0.892857
747,where does the electron transport chain pumps ...,2168,"['across a membrane', 'mitochondrial membrane']",inner mitochondrial membrane,"['total', 'no_answer_overlap']",False,0.800000,0.59817,0.892857
562,what is the full form of ib board,1584,"['International Baccalaureate', 'The Internati...",International Baccalaureate Organization,"['total', 'no_answer_overlap']",False,0.800000,0.77375,0.892857
497,who pays medical bills in great britain where ...,1400,"['general taxation', 'taxes']",general taxation system,"['total', 'no_answer_overlap']",False,0.800000,0.79533,0.892857
920,who was elected president in mexico in 2000,2721,['Vicente Fox'],Vicente Fox Quesada,"['total', 'no_answer_overlap', 'question_overl...",False,0.800000,0.55825,0.892857
161,who wrote the original little red riding hood ...,435,['Charles Perrault'],French author Charles Perrault,"['total', 'no_answer_overlap']",False,0.666667,0.74315,0.852273
467,where was the u.s.s maine when it exploded in ...,1309,['Havana Harbor'],"Havana Harbor, Cuba","['total', 'no_answer_overlap']",False,0.800000,0.68916,0.852273
967,who votes in the baseball hall of fame,2870,"['or the Veterans Committee', 'Veterans Commit...",members of the Veterans Committee,"['total', 'no_answer_overlap']",False,0.666667,0.68172,0.815217
745,who plays general hux in the last jedi,2165,['Domhnall Gleeson'],Domhnall Gleeson as General Hux,"['total', 'no_answer_overlap']",False,0.571429,0.54206,0.815217
1139,how much does a new gulfstream g650 cost,3345,"['US $ 66.61 million', '$66.5 million']",$66.61 million,"['total', 'no_answer_overlap', 'question_overl...",False,0.800000,0.83101,0.754986
653,when does jim propose to pam on the office,1837,['In the Season 5 premiere'],in the season eight premiere,"['total', 'no_answer_overlap']",False,0.750000,0.80807,0.750000
307,when does canada switch to daylight savings time,828,['the second Sunday of March'],the second Sunday in March,"['total', 'no_answer_overlap']",False,0.750000,0.95117,0.750000
800,one piece english dubbed episode 564 release date,2340,"['September 16 , 2012']","September 16, 2018","['total', 'no_answer_overlap', 'no_question_ov...",False,0.666667,0.50892,0.736111
666,what is the meaning of auv in cars,1887,['action utility vehicles'],utility vehicle,"['total', 'no_answer_overlap', 'no_question_ov...",False,0.400000,0.57912,0.646552
839,where did immigrants enter the us on the west ...,2489,"['Angel Island Immigration Station', 'San Fran...",San Francisco,"['total', 'no_answer_overlap', 'no_question_ov...",False,0.800000,0.72439,0.646552
12,what type of car is a jeep considered,32,"['off - road vehicles', 'sport utility vehicle...",utility vehicle,"['total', 'no_answer_overlap']",False,0.400000,0.69056,0.646552
847,1 . what was the precursor to the present day ...,2513,['the ARPANET project'],the ARPANET,"['total', 'no_answer_overlap']",False,0.666667,0.73263,0.646552
1071,when did dragon ball super tournament of power...,3154,"['February 19 , 2017']","February 5, 2017","['total', 'no_answer_overlap']",False,0.666667,0.69130,0.638889
102,fast & furious 8 release date in india,262,"['April 12 , 2017']","April 14, 2017","['total', 'no_answer_overlap']",False,0.666667,0.68709,0.638889
165,what is the average height of a chinese man,442,['5 ft 6 in'],5 ft 10 in,"['total', 'no_answer_overlap']",False,0.750000,0.90364,0.638889
742,royal society for the protection of birds numb...,2148,['more than a million'],more than 6 million,"['total', 'no_answer_overlap']",False,0.857143,0.75107,0.638889
168,when did the first pair of yeezys come out,447,"['February 14 , 2015']","February 13, 2015","['total', 'no_answer_overlap']",False,0.666667,0.70211,0.638889
1053,what was guantanamo bay before it was a prison,3117,['Guantanamo Bay Naval Base'],Naval Station Guantanamo Bay,"['total', 'no_answer_overlap']",False,0.750000,0.55412,0.638889
159,where does the ohio river and the mississippi ...,430,"['Cairo , Illinois']","Pittsburgh, Illinois","['total', 'no_answer_overlap']",False,0.500000,0.44069,0.625000
391,where are the san juan mountains in new mexico,1053,['northwestern New Mexico'],northern New Mexico,"['total', 'no_answer_overlap']",False,0.666667,0.86437,0.625000
1214,first dynasty to issue gold coins in india,3575,['The Gupta Empire'],the Gupta dynasty,"['total', 'no_answer_overlap']",False,0.500000,0.75220,0.625000
413,when did the first battle of ypres end,1143,['22 November 1914'],30 November 1914,"['total', 'no_answer_overlap']",False,0.666667,0.94158,0.625000
618,what is a coherent set of values and beliefs a...,1729,"['a political ideology', 'political ideology',...",a political philosophy,"['total', 'no_answer_overlap']",False,0.500000,0.82127,0.625000
616,what is the strongest earthquake in the united...,1726,"['1964 Alaska earthquake and tsunami', '1700 C...",1964 Alaska earthquake,"['total', 'no_answer_overlap', 'question_overl...",False,0.750000,0.77546,0.613426
516,who was assassinated during a visit to sarajev...,1462,['Archduke Franz Ferdinand of Austria'],Archduke Franz Ferdinand,"['total', 'no_answer_overlap', 'no_question_ov...",False,0.750000,0.82541,0.613426
662,the first significant restriction on free immi...,1872,"['Naturalization Act of 1790', 'Chinese Exclus...",Chinese Exclusion Act,"['total', 'no_answer_overlap']",False,0.750000,0.70799,0.613426
817,the art and science of making objects from cla...,2403,"['Ceramic art', 'Ceramic']",ceramics,"['total', 'no_answer_overlap']",False,0.000000,0.26669,0.500000
1153,who are the only 2 families that have had 3 ge...,3395,"['Farrow / Previn / Allens', 'the Coppolas', '...",Coppola,"['total', 'no_answer_overlap', 'no_question_ov...",False,0.000000,0.41626,0.500000
802,what happens when iron reacts with oxygen and ...,2352,['Rust'],rusting,"['total', 'no_answer_overlap', 'no_question_ov...",False,0.000000,0.01402,0.500000
586,the complete collection of dna and genes is ca...,1655,"['genome', 'chromosome']",chromosomes,"['total', 'no_answer_overlap']",False,0.000000,0.86578,0.500000
258,what was the religion in persia before islam,700,"['Zoroastrian', 'the Zoroastrian religion']",Zoroastrianism,"['total', 'no_answer_overlap', 'no_question_ov...",False,0.000000,0.74501,0.500000
645,what started the war between us and japan,1814,['attack on Pearl Harbor'],Pearl Harbor,"['total', 'no_answer_overlap']",False,0.666667,0.45082,0.493421
103,the group that officially elects the president...,263,"['the U.S. Electoral College', 'U.S. Electoral...",Electoral College,"['total', 'no_answer_overlap']",False,0.800000,0.58812,0.493421
15,where does the story the great gatsby take place,39,['Long Island of 1922'],Long Island,"['total', 'no_answer_overlap']",False,0.666667,0.57017,0.493421
322,where was 2017 beauty and the beast filmed,870,"['Surrey , United Kingdom']","Surrey, England","['total', 'no_answer_overlap']",False,0.400000,0.67467,0.480769
127,what genre is the magic tree house books,342,"[""Children 's historical fantasy""]",children's novel,"['total', 'no_answer_overlap']",False,0.000000,0.37944,0.480769
355,where do the secretory cells of endocrine glan...,954,"['epithelial surface', 'directly into the bloo...",into the blood,"['total', 'no_answer_overlap']",False,0.400000,0.53333,0.480769

In [76]:
import numpy as np

In [77]:
np.corrcoef(list(results['bert_score']), list(results['meteor_score']))

array([[1.        , 0.76750884],
       [0.76750884, 1.        ]])

In [78]:
np.corrcoef(list(no_overlap['bert_score']), list(no_overlap['meteor_score']))

array([[1.        , 0.50711702],
       [0.50711702, 1.        ]])

In [81]:
np.corrcoef(list(no_overlap['meteor']), list(no_overlap['exact_match']))

KeyError: 'meteor'

In [79]:
from scipy.stats.stats import pearsonr

/var/folders/5c/rh_j56vx44n9xrrr4x_wcf0m0000gn/T/ipykernel_55294/2554227351.py:1: DeprecationWarning: Please use `pearsonr` from the `scipy.stats` namespace, the `scipy.stats.stats` namespace is deprecated.
  from scipy.stats.stats import pearsonr

In [80]:
pearsonr(list(no_overlap['bert_score']), list(no_overlap['meteor_score'])) # proves correlation is significant!

(0.5071170150111484, 2.0575498323099597e-81)